import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Management",
    moduleName: "managements",
    iconType: "material-icons-two-tone",
    icon: "local_police",
    class: "menu-toggle",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/managements/all-operations",
        title: "OperationClaim",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        claim: "GetOperationClaimsQuery",
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/managements/languages",
        title: "Languages",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetLanguagesQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/managements/translates",
        title: "Translates",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetTranslatesQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/managements/groups",
        title: "Groups",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetGroupsQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/managements/logs",
        title: "Log",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetLogDtoQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/managements/users",
        title: "Users",
        moduleName: "managements",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetUsersQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "--FrequentlyUsedSpaces",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    claim: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/admin/dashboard/main",
    title: "Homepage",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/admin/patients/search-patient",
    title: "SearchPatient",
    moduleName: "patients",
    iconType: "material-icons-two-tone",
    icon: "search",
    class: "",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/admin/patients/add-patient",
    title: "AddNewPatient",
    moduleName: "patients",
    iconType: "material-icons-two-tone",
    icon: "person_add",
    class: "",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/admin/appointments/all-appointments",
    title: "AppointmentList",
    moduleName: "appointments",
    iconType: "material-icons-two-tone",
    icon: "insert_invitation",
    class: "",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },

  // Admin Modules
  {
    path: "",
    title: "--Menu",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    claim: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "",
    title: "Appointments",
    moduleName: "appointments",
    iconType: "material-icons-two-tone",
    icon: "assignment",
    class: "menu-toggle",
    claim:'GetAppointmentsDtoAllQuery',
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/appointments/add-appointment-list",
        title: "AddAppointmentList",
        moduleName: "appointments",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"CreateAppointmentListCommand",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/appointments/all-appointments",
        title: "AppointmentList",
        moduleName: "appointments",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"GetAppointmentsDtoAllQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Patients",
    moduleName: "patients",
    iconType: "material-icons-two-tone",
    icon: "face",
    class: "menu-toggle",
    claim:"GetPatientDatasQuery",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/patients/all-patients",
        title: "PatientProcesses",
        moduleName: "patients",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"GetPatientDatasQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/patients/add-patient",
        title: "AddDetailedPatient",
        moduleName: "patients",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"CreatePatientDataCommand",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/patients/search-patient",
        title: "SearchPatient",
        moduleName: "patients",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"GetPatientDatasQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Departments",
    moduleName: "departments",
    iconType: "material-icons-two-tone",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    claim:'GetDepartmentsQuery',
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/departments/all-departments",
        title: "DepartmentProcesses",
        moduleName: "departments",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:'GetDepartmentsQuery',
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      // {
      //   path: "/admin/departments/add-department",
      //   title: "Detaylı Departman Ekleme",
      //   moduleName: "departments",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   claim:
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   submenu: [],
      // },
    ]
  },
  {
    path: "",
    title: "Doctors",
    moduleName: "doctors",
    iconType: "material-icons-two-tone",
    icon: "supervised_user_circle",
    class: "menu-toggle",
    claim:"GetDoctorsAllDtoQuery",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/doctors/all-doctors",
        title: "DoctorProcesses",
        moduleName: "doctors",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"GetDoctorsAllDtoQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/doctors/add-doctor",
        title: "AddDetailedDoctor",
        moduleName: "doctors",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:"CreateDoctorCommand",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Institutions",
    moduleName: "institutions",
    iconType: "material-icons-two-tone",
    icon: "location_city",
    class: "menu-toggle",
    groupTitle: false,
    claim:'GetInstitutionsQuery',
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/institutions/all-institutions",
        title: "InstitueProcesses",
        moduleName: "institutions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:'GetInstitutionsQuery',
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ]
  },
  {
    path: "",
    title: "Protocols",
    moduleName: "protocols",
    iconType: "material-icons-two-tone",
    icon: "format_list_numbered",
    class: "menu-toggle",
    claim:'',
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/protocols/all-protocols",
        title: "ProtocolProcesses",
        moduleName: "protocols",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:'GetProtocolDtosQuerys',
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/protocols/all-protocoltypes",
        title: "ProtocolTypes",
        moduleName: "protocols",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        claim:'GetProtocolTypesQuery',
        badge: "",
        badgeClass: "",
        submenu: [],
      }
    ]
  },
  {
    path: "",
    title: "Processes",
    moduleName: "processes",
    iconType: "material-icons-two-tone",
    icon: "widgets",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    claim:'',
    badgeClass: "",
    submenu: [
      {
        path: "/admin/processes/all-process-groups",
        title: "ProcessGroups",
        moduleName: "processes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim:'GetProcessGroupsQuery',
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/processes/institue-process-save",
        title: "ProcessProcesses",
        moduleName: "processes",
        iconType: "",
        icon: "",
        claim:'GetProcessInstituesQuery',
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/processes/all-processes",
        title: "SearchProcess",
        moduleName: "processes",
        iconType: "",
        icon: "",
        claim:'GetProcessInstituesQuery',
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Options",
    moduleName: "options",
    iconType: "material-icons-two-tone",
    icon: "settings",
    class: "menu-toggle",
    claim: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/options/all-protocol-type-processes",
        title: "ProtocolTypeProcesses",
        moduleName: "options",
        iconType: "",
        icon: "",
        claim: "GetProtocolTypeProcessesQuery",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/options/creatable-forms",
        title: "CreatableForm",
        moduleName: "options",
        iconType: "",
        icon: "",
        claim: "GetFormTablesQuery",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/admin/options/optional-settings",
        title: "OptionalProcessSettings",
        moduleName: "options",
        iconType: "",
        icon: "",
        class: "ml-menu",
        claim: "GetOptionalSettingsQuery",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },

  // // Doctor Modules
  // {
  //   path: '/doctor/dashboard',
  //   title: 'Dashboard',
  //   moduleName: 'dashboard',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'home',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // {
  //   path: "/doctor/appointments/all-appointments",
  //   title: "Randevularım",
  //   moduleName: "appointments",
  //   iconType: "material-icons-two-tone",
  //   icon: "assignment",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },

  // // Patient Modules
  // {
  //   path: '/patient/dashboard',
  //   title: 'Dashboard',
  //   moduleName: 'dashboard',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'home',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // // Common Modules

  // {
  //   path: '',
  //   title: 'Authentication',
  //   moduleName: 'authentication',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'supervised_user_circle',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: '/authentication/signin',
  //       title: 'Sign In',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/authentication/signup',
  //       title: 'Sign Up',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/authentication/forgot-password',
  //       title: 'Forgot Password',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/authentication/locked',
  //       title: 'Locked',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/authentication/page404',
  //       title: '404 - Not Found',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/authentication/page500',
  //       title: '500 - Server Error',
  //       moduleName: 'authentication',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: '',
  //   title: 'Extra Pages',
  //   moduleName: 'extra-pages',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'description',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: '/extra-pages/blank',
  //       title: 'Blank Page',
  //       moduleName: 'extra-pages',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: '',
  //   title: 'Multi level Menu',
  //   moduleName: 'multilevel',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'slideshow',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: '/multilevel/first1',
  //       title: 'First',
  //       moduleName: 'multilevel',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/',
  //       title: 'Second',
  //       moduleName: 'secondlevel',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-sub-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [
  //         {
  //           path: '/multilevel/secondlevel/second1',
  //           title: 'Second 1',
  //           moduleName: 'secondlevel',
  //           iconType: '',
  //           icon: '',
  //           class: 'ml-sub-sub-menu',
  //           groupTitle: false,
  //           badge: '',
  //           badgeClass: '',
  //           submenu: [],
  //         },
  //         {
  //           path: '/multilevel/secondlevel/second2',
  //           title: 'Second 2',
  //           moduleName: 'secondlevel',
  //           iconType: '',
  //           icon: '',
  //           class: 'ml-sub-sub-menu',
  //           groupTitle: false,
  //           badge: '',
  //           badgeClass: '',
  //           submenu: [],
  //         },
  //       ],
  //     },
  //     {
  //       path: '/multilevel/first3',
  //       title: 'Third',
  //       moduleName: 'multilevel',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: '/authentication/signin',
  //   title: 'Logout',
  //   moduleName: 'logout',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'power_settings_new',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
];
